This notebook provides examples to go along with the [textbook](http://manipulation.csail.mit.edu/robot.html).  I recommend having both windows open, side-by-side!

In [1]:
import numpy as np
from pydrake.all import PackageMap, Parser, RobotDiagramBuilder, Simulator, StartMeshcat

from manipulation import running_as_notebook
from manipulation.make_drake_compatible_model import MakeDrakeCompatibleModel
from manipulation.remotes import AddGymnasiumRobotics
from manipulation.utils import ApplyDefaultVisualization

In [2]:
# Start the visualizer.
meshcat = StartMeshcat()

INFO:drake:Meshcat listening for connections at http://localhost:7006


## Gymnasium Robotics

Includes the following environments:
- Franka kitchen
- ...

In [3]:
# TODO(russt): Use ModelVisualizer pending resolution of Drake#22444.
if running_as_notebook:  # I don't want to download the repo in CI.
    meshcat.Delete()
    builder = RobotDiagramBuilder()
    plant = builder.plant()
    parser = Parser(plant)
    package_map = parser.package_map()
    AddGymnasiumRobotics(package_map)
    original_file = package_map.ResolveUrl(
        "package://gymnasium_robotics/kitchen_franka/kitchen_assets/kitchen_env_model.xml"
    )
    drake_compatible_file = original_file.replace(".xml", ".drake.xml")
    MakeDrakeCompatibleModel(original_file, drake_compatible_file)
    model_instances = parser.AddModels(drake_compatible_file) # type: ignore
    plant.Finalize()
    ApplyDefaultVisualization(builder.builder(), meshcat=meshcat)
    diagram = builder.Build()
    simulator = Simulator(diagram) # type: ignore

    # Workaround for drake#22444: set the desired state to zero.
    for model_instance in model_instances:
        desired_state_port = plant.get_desired_state_input_port(model_instance)
        if desired_state_port.size() > 0:
            desired_state_port.FixValue(
                plant.GetMyContextFromRoot(simulator.get_context()),
                np.zeros(desired_state_port.size()), # type: ignore
            )

    diagram.ForcedPublish(simulator.get_context()) # type: ignore

INFO:drake:PackageMap: Downloading https://github.com/Farama-Foundation/Gymnasium-Robotics/archive/refs/tags/v1.3.1.tar.gz


Processing include file: basic_scene.xml
Processing include file: ../franka_assets/assets.xml
Processing include file: ../franka_assets/actuator.xml
Processing include file: item_assets/oven_asset.xml
Processing include file: item_assets/counters_asset.xml
Processing include file: item_assets/backwall_asset.xml
Processing include file: item_assets/slidecabinet_asset.xml
Processing include file: item_assets/hingecabinet_asset.xml
Processing include file: item_assets/microwave_asset.xml
Processing include file: item_assets/kettle_asset.xml
Processing include file: ../franka_assets/chain.xml
Processing include file: item_assets/counters_chain.xml
Processing include file: item_assets/oven_chain.xml
Processing include file: item_assets/backwall_chain.xml
Processing include file: item_assets/slidecabinet_chain.xml
Processing include file: item_assets/hingecabinet_chain.xml
Processing include file: item_assets/microwave_chain.xml
Processing include file: item_assets/kettle_chain.xml
Converted

 mass = 0.0001728296027885505
 Center of mass = [-2.688281036057395e-08  -3.58959082630924e-08  0.00987339913766482]
 Inertia about point P, I_BP =
[ 1.54599e-06  -4.84922e-13   5.45393e-14]
[-4.84922e-13   1.54599e-06  -2.29619e-13]
[ 5.45393e-14  -2.29619e-13    3.0596e-06]
 Inertia about center of mass, I_BBcm =
[ 1.52914e-06  -4.84922e-13   8.66607e-15]
[-4.84922e-13   1.52914e-06  -2.90872e-13]
[ 8.66607e-15  -2.90872e-13    3.0596e-06]
 Principal moments of inertia about Bcm (center of mass) =
[1.5291376783190582e-06  1.5291389170603102e-06  3.059598537974587e-06]



Converted /private/var/tmp/.cache_zhangjian/drake/package_map/d274b3ee1d34337aa35d4686447fda6a6d20dfcb4d375eab91b4e49b1108afde-df2831136df60ca29f5fe992a45e2c09e7fc0d96537b0f69c919aa0376a75282/kitchen_franka/kitchen_assets/../franka_assets/meshes/../../kitchen_assets/meshes/microfeet.stl to /private/var/tmp/.cache_zhangjian/drake/package_map/d274b3ee1d34337aa35d4686447fda6a6d20dfcb4d375eab91b4e49b1108afde-df2831136df60ca29f5fe992a45e2c09e7fc0d96537b0f69c919aa0376a75282/kitchen_franka/kitchen_assets/../franka_assets/meshes/../../kitchen_assets/meshes/microfeet_from_stl.obj
Converted /private/var/tmp/.cache_zhangjian/drake/package_map/d274b3ee1d34337aa35d4686447fda6a6d20dfcb4d375eab91b4e49b1108afde-df2831136df60ca29f5fe992a45e2c09e7fc0d96537b0f69c919aa0376a75282/kitchen_franka/kitchen_assets/../franka_assets/meshes/../../kitchen_assets/meshes/microhandle.stl to /private/var/tmp/.cache_zhangjian/drake/package_map/d274b3ee1d34337aa35d4686447fda6a6d20dfcb4d375eab91b4e49b1108afde-df2831136df6